### ISSUE TITLE
Problem importing General Ledger

### ISSUE THREAD

**Issue by SamirSaidani** [grap/odoo-addons-cae#2]
Hi,

I've tried to import a general ledger into our fresh new database, and we have some problem importing a general ledger.
Step to reproduce : 
1. Import a general ledger logged into admin account: Adviser>Journal Entries>Import (see attachment for testing).
2. Hit Validate or Import

-> Error:  
`Unknown error during import: <class 'odoo.exceptions.ValidationError'>: (u"You can't affect the item / (model 'account.move') to a fiscal mother company.", None) at row 2
Resolve other errors first`

[TEST - GL2017.xlsx](https://github.com/odoo-cae/odoo-addons-cae/files/2864601/TEST.-.GL2017.xlsx)

**Comment by legalsylvain** [comment]
Hi @samir-s. 

Indeed, this is normal by design. moves should be associated to a "child company" not the "mother company".

Ref : [link](https://github.com/odoo-cae/odoo-addons-cae/tree/10.0/fiscal_company_base
)
> Accounting moves of the child companies are written in the child company, but associated to the account of the parent company.

**solution**

- change the company of the account move, and set a child company, should solve the problem.

**Comment by SamirSaidani** [comment]
you're right, thanks a lot, it worked like a charm.
